### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by askingalot** [KelleyCrittenden/Csharp-Shooting-Dice#2]
This doesn't need to be public
https://github.com/KelleyCrittenden/Csharp-Shooting-Dice/blob/a57c55e6cd237b817d734d53199f8f983eabfe32/CreativeSmackTalkingPlayer.cs#L9-L18

You should make instances of each type of Player and add them to the list so they can be tested.
https://github.com/KelleyCrittenden/Csharp-Shooting-Dice/blob/a57c55e6cd237b817d734d53199f8f983eabfe32/Program.cs#L42-L51

Small thing, but you don't need the parentheses
https://github.com/KelleyCrittenden/Csharp-Shooting-Dice/blob/a57c55e6cd237b817d734d53199f8f983eabfe32/SmackTalkingPlayer.cs#L10

**Comment by KelleyCrittenden** [comment]
Got it! Thanks Andy!
